### ISSUE TITLE
Custom Icons section, suggested edit<title>

### ISSUE THREAD

**Issue by makanimike** [ajnart/homarr-docs#12]
### Environment

Docker

### Describe the problem

hi, great work. I am going through a few different home pages and I think I will stick with yours! :)

tiny suggestion/edit for the documention in the Custom Icons section,
https://homarr.dev/docs/advanced-configuration/custom-icons

You write: 
`Icons are requested in the following way:

Grab Name
Replace " " with "-"
Convert to lowercase
Insert in link: https://cdn.jsdelivr.net/gh/walkxhub/dashboard-icons/png/{name}.png`

It would read easier if you said: "Icons are requested in one of the following ways"  
I was puzzling over that for a few minutes until I figured it out with some trial and error.

### Please tick the boxes

- [X] You've read the [docs](https://github.com/ajnart/homarr#readme)
- [X] You've checked for [duplicate issues](https://github.com/ajnart/homarr/issues)
- [X] You've tried to debug yourself

**Comment by ajnart** [comment]
Hey ! Sorry just finding this out now. Can you do the modifications on the page directly with the top left "edit page" button ?

**Comment by makanimike** [comment]
I don't seem to have that activated in my view. I do not see any editing function....
