### ISSUE TITLE
Uploaded images 404, they need a container restart.

### ISSUE THREAD

**Issue by Aincvy** [ajnart/homarr-docs#64]
### Environment

Docker

### Version

0.12.3

### Describe the problem

1.  add new data mapping.  `- ./data/img:/app/public/img`
2. upload image to ./data/img/  ,  png/jpg file.
3. change background to `/img/1.png`
4. press F12, 404 console message
5. try visit `http://debian.mylab:7575/img/1.png` directly, 404 got.
6. I can see thoes images in docker ash.
7. restart container from portainer.
8. it works. 

https://homarr.dev/docs/customizations/page-design#custom-background doesn't mention, it needs a restart to take effect.

And the transparency of the panel seems to be unable to be adjusted.

### Please tick the boxes

- [X] You've read the [docs](https://github.com/ajnart/homarr#readme)
- [X] You've checked for [duplicate issues](https://github.com/ajnart/homarr/issues)
- [X] You've tried to debug yourself

**Comment by manuel-rw** [comment]
This page here mentions it: https://homarr.dev/docs/customizations/icons#using-your-icons
Can you adjust the documentation in the background page? You don't need any programming skills for that :)

**Comment by Aincvy** [comment]
Fork, change, and PR ?

**Comment by manuel-rw** [comment]
Yes. We also have a "Edit this page" at every page at the bottom of the documentation. You can use that so you don't have to search for the file. I will review the PR once you submit it :)

**Comment by Aincvy** [comment]
Sure, I will give it a try later, today or tomorrow.

**Comment by manuel-rw** [comment]
Closing, because PR has been merged
